# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TLDR Dev Notes
tagline: Aamnah's developer notes
email: hello@aamnah.com
description: > # this means to ignore newlines until "baseurl:"
  Please note that this site and the posts on it are, and will always be, a work in progress. If i waited for perfection, i’d never get anything done.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tldrdevnotes.com" # the base hostname & protocol for your site

destination: ./docs

github_url: "https://github.com/aamnah/tldrdevnotes.com/blob/master/"
# Social
twitter_username: AamnahAkram
github_username:  Aamnah

# Build settings
markdown: redcarpet

redcarpet:
  extension: [
    "no_intra_emphasis",
    "tables",
    "autolink",
    "strikethrough",
    "with_toc_data"
  ]

# Collections
collections:
  api:
    output: true
    title: "APIs"
    permalink: /:collection/:path/
  aws:
    output: true
    title: "Amazon Web Services (AWS)"
    permalink: /:collection/:path/
  bash-scripting:
    output: true
    title: "Bash Scripting"
    permalink: /:collection/:path/
  cheatsheets:
    output: true
    title: "Cheatsheets"
    permalink: /:collection/:path/
  commands:
    output: true
    title: "Commands"
    permalink: /:collection/:path/
  css-sass:
    output: true
    title: "CSS and Sass"
    permalink: /:collection/:path/
  databases:
    output: true
    title: "Databases"
    permalink: /:collection/:path/
  git-github:
    output: true
    title: "Git and Github"
    permalink: /:collection/:path/
  ios-swift:
    output: true
    title: "iOS and Swift"
    permalink: /:collection/:path/
  javascript:
    output: true
    title: "JavaScript"
    permalink: /:collection/:path/
  jekyll:
    output: true
    title: "Jekyll"
    permalink: /:collection/:path/
  linux:
    output: true
    title: "Linux"
    permalink: /:collection/:path/
  misc:
    output: true
    title: "Misc."
    permalink: /:collection/:path/
  php:
    output: true
    title: "PHP"
    permalink: /:collection/:path/
  python:
    output: true
    title: "Python"
    permalink: /:collection/:path/
  quotes:
    output: true
    permalink: /:collection/:path/  
  raspberrypi:
    output: true
    title: "Raspberry Pi"
    permalink: /:collection/:path/
  webdev:
    output: true
    title: "Web Development"
    permalink: /:collection/:path/
  workflow:
    output: true
    title: "Workflow"
    permalink: /:collection/:path/

# Site wide defaults
defaults:
- scope:
    path: "" # an empty string here means all files in the project
    type: "posts" # types that are available are pages, posts, drafts or any collection in your site. 
  values:
    layout: "post"
    author: "Aamnah"

- scope:
    path: "_posts"
    type: "posts" # types that are available are pages, posts, drafts or any collection in your site.
  values:
    layout: "post"

- scope:
    path: "_cheatseets"
    type: "cheatsheets" # a collection in your site, in plural form
  values:
    layout: "post"

- scope:
    path: "_commands"
    type: "commands"
  values:
    layout: "post"
