# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TLDR Dev Notes
tagline: Aamnah's developer notes
email: hello@aamnah.com
description: > # this means to ignore newlines until "baseurl:"
  Please note that this site and the posts on it are, and will always be, a work in progress. If i waited for perfection, i’d never get anything done.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tldrdevnotes.com" # the base hostname & protocol for your site

destination: ./docs

# Social
twitter_username: AamnahAkram
github_username:  Aamnah

# Build settings
markdown: redcarpet

redcarpet:
  extension: [
    "no_intra_emphasis",
    "tables",
    "autolink",
    "strikethrough",
    "with_toc_data"
  ]

# Collections
collections:
  - resource
  - quote

# Site wide defaults
defaults:
- scope:
    path: "_posts" # an empty string here means all files in the project
    type: "posts" 
  values:
    layout: "post"
    author: "Aamnah"

- scope:
    path: ""
    type: "resource"
  values:
    layout: "resource"

- scope:
    path: ""
    type: "quote"
  values:
    layout: "quote"