# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TLDR Dev Notes
tagline: Aamnah's developer notes
email: hello@aamnah.com
description: > # this means to ignore newlines until "baseurl:"
  Please note that this site and the posts on it are, and will always be, a work in progress. If i waited for perfection, i’d never get anything done.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tldrdevnotes.com" # the base hostname & protocol for your site

destination: ./docs

github_url: "https://github.com/aamnah/tldrdevnotes.com/blob/master/"
# Social
twitter_username: AamnahAkram
github_username:  Aamnah

# Misc. Settings
timezone: Asia/Karachi

# Build settings

# markdown: redcarpet

# redcarpet:
#   extension: [
#     "no_intra_emphasis",
#     "tables",
#     "autolink",
#     "strikethrough",
#     "with_toc_data"
#   ]

markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable : true

# Collections
# permalink default for collections is /:collection/:path/:title:output_ext
collections:
  api:
    output: true
    title: "APIs"
  aws:
    output: true
    title: "Amazon Web Services (AWS)"
  bash-scripting:
    output: true
    title: "Bash Scripting"
  cheatsheets:
    output: true
    title: "Cheatsheets"
  commands:
    output: true
    title: "Commands"
  css-sass:
    output: true
    title: "CSS and Sass"
  databases:
    output: true
    title: "Databases"
  git-github:
    output: true
    title: "Git and Github"
  ios-swift:
    output: true
    title: "iOS and Swift"
  javascript:
    output: true
    title: "JavaScript"
  jekyll:
    output: true
    title: "Jekyll"
  linux:
    output: true
    title: "Linux"
  misc:
    output: true
    title: "Misc."
  nodejs:
    output: true
    title: "Node.js"
  opencart:
    output: true
    title: "OpenCart"
  php:
    output: true
    title: "PHP"
  programming:
    output: true
    title: "Programming"
  python:
    output: true
    title: "Python"
  quotes:
    output: true  
  raspberrypi:
    output: true
    title: "Raspberry Pi"
  sysadmin:
    output: true
    title: "Sys Admin"
  webdev:
    output: true
    title: "Web Development"
  workflow:
    output: true
    title: "Workflow"

# Site wide defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # types that are available are pages, posts, drafts or any collection in your site. 
    values:
      layout: "post"
      author: "Aamnah"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      type: "bash-scripting"
    values:
      layout: "post"
  - 
    scope:
      path: "_cheatseets"
      type: "cheatsheets" # a collection in your site, in plural form
    values:
      layout: "post"
  -
    scope:
      path: "_commands"
      type: "commands"
    values:
      layout: "post"
  -
    scope:
      type: "linux" # linux collection in './_linux' folder
    values:
      layout: "post"
  -
    scope:
      path: "_nodejs"
      type: "nodejs"
    values:
      layout: "post"
  -
    scope:
      type: "opencart"
    values:
      layout: "post"
  -
    scope:
      type: "sysadmin"
    values:
      layout: "post"
  -
    scope:
      type: "workflow"
    values:
      layout: "post"